Class ExtremeAPI.Controller.Abstract Extends %RegisteredObject [ Abstract ]
{

Projection ExtremeAPIController As ExtremeAPI.Projection.Controller(ROOTPACKAGENAME = "generatedClasses");

Projection JavaSpec As ExtremeAPI.Projection.JavaSpec(ROOTPACKAGENAME = "generatedClasses", TARGETDIR = "D:\_git\personal\java-cache-gateway-example\cache-projection\src\main\resources\", TYPE = "Controller");

}

